//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Proxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Model")]
    public partial class Photo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreationDateField;
        
        private MyPhotos.Proxy.Event[] EventsField;
        
        private int IdField;
        
        private bool IsDeletedField;
        
        private MyPhotos.Proxy.Landscape[] LandscapesField;
        
        private string NameField;
        
        private string PathField;
        
        private MyPhotos.Proxy.Person[] PersonsField;
        
        private MyPhotos.Proxy.Place[] PlacesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Event[] Events
        {
            get
            {
                return this.EventsField;
            }
            set
            {
                this.EventsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Landscape[] Landscapes
        {
            get
            {
                return this.LandscapesField;
            }
            set
            {
                this.LandscapesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Person[] Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                this.PersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Place[] Places
        {
            get
            {
                return this.PlacesField;
            }
            set
            {
                this.PlacesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Model")]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> DateField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private MyPhotos.Proxy.Photo[] PhotosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Photo[] Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Landscape", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Model")]
    public partial class Landscape : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private MyPhotos.Proxy.Photo[] PhotosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Photo[] Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Model")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private MyPhotos.Proxy.Photo[] PhotosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Photo[] Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos.Model")]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private MyPhotos.Proxy.Photo[] PhotosField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotos.Proxy.Photo[] Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPhotoController")]
public interface IPhotoController
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/AddOrUpdatePhoto", ReplyAction="http://tempuri.org/IPhotoController/AddOrUpdatePhotoResponse")]
    void AddOrUpdatePhoto(MyPhotos.Proxy.Photo photoToAddOrUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/AddOrUpdatePhoto", ReplyAction="http://tempuri.org/IPhotoController/AddOrUpdatePhotoResponse")]
    System.Threading.Tasks.Task AddOrUpdatePhotoAsync(MyPhotos.Proxy.Photo photoToAddOrUpdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/SearchPhotoByText", ReplyAction="http://tempuri.org/IPhotoController/SearchPhotoByTextResponse")]
    MyPhotos.Proxy.Photo[] SearchPhotoByText(string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/SearchPhotoByText", ReplyAction="http://tempuri.org/IPhotoController/SearchPhotoByTextResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Photo[]> SearchPhotoByTextAsync(string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/DeletePhoto", ReplyAction="http://tempuri.org/IPhotoController/DeletePhotoResponse")]
    void DeletePhoto(MyPhotos.Proxy.Photo photoToDelete);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/DeletePhoto", ReplyAction="http://tempuri.org/IPhotoController/DeletePhotoResponse")]
    System.Threading.Tasks.Task DeletePhotoAsync(MyPhotos.Proxy.Photo photoToDelete);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPhotos", ReplyAction="http://tempuri.org/IPhotoController/GetAllPhotosResponse")]
    MyPhotos.Proxy.Photo[] GetAllPhotos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPhotos", ReplyAction="http://tempuri.org/IPhotoController/GetAllPhotosResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Photo[]> GetAllPhotosAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPersons", ReplyAction="http://tempuri.org/IPhotoController/GetAllPersonsResponse")]
    MyPhotos.Proxy.Person[] GetAllPersons();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPersons", ReplyAction="http://tempuri.org/IPhotoController/GetAllPersonsResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Person[]> GetAllPersonsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllEvents", ReplyAction="http://tempuri.org/IPhotoController/GetAllEventsResponse")]
    MyPhotos.Proxy.Event[] GetAllEvents();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllEvents", ReplyAction="http://tempuri.org/IPhotoController/GetAllEventsResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Event[]> GetAllEventsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllLandscapes", ReplyAction="http://tempuri.org/IPhotoController/GetAllLandscapesResponse")]
    MyPhotos.Proxy.Landscape[] GetAllLandscapes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllLandscapes", ReplyAction="http://tempuri.org/IPhotoController/GetAllLandscapesResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Landscape[]> GetAllLandscapesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPlaces", ReplyAction="http://tempuri.org/IPhotoController/GetAllPlacesResponse")]
    MyPhotos.Proxy.Place[] GetAllPlaces();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoController/GetAllPlaces", ReplyAction="http://tempuri.org/IPhotoController/GetAllPlacesResponse")]
    System.Threading.Tasks.Task<MyPhotos.Proxy.Place[]> GetAllPlacesAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPhotoControllerChannel : IPhotoController, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PhotoControllerClient : System.ServiceModel.ClientBase<IPhotoController>, IPhotoController
{
    
    public PhotoControllerClient()
    {
    }
    
    public PhotoControllerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PhotoControllerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PhotoControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddOrUpdatePhoto(MyPhotos.Proxy.Photo photoToAddOrUpdate)
    {
        base.Channel.AddOrUpdatePhoto(photoToAddOrUpdate);
    }
    
    public System.Threading.Tasks.Task AddOrUpdatePhotoAsync(MyPhotos.Proxy.Photo photoToAddOrUpdate)
    {
        return base.Channel.AddOrUpdatePhotoAsync(photoToAddOrUpdate);
    }
    
    public MyPhotos.Proxy.Photo[] SearchPhotoByText(string text)
    {
        return base.Channel.SearchPhotoByText(text);
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Photo[]> SearchPhotoByTextAsync(string text)
    {
        return base.Channel.SearchPhotoByTextAsync(text);
    }
    
    public void DeletePhoto(MyPhotos.Proxy.Photo photoToDelete)
    {
        base.Channel.DeletePhoto(photoToDelete);
    }
    
    public System.Threading.Tasks.Task DeletePhotoAsync(MyPhotos.Proxy.Photo photoToDelete)
    {
        return base.Channel.DeletePhotoAsync(photoToDelete);
    }
    
    public MyPhotos.Proxy.Photo[] GetAllPhotos()
    {
        return base.Channel.GetAllPhotos();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Photo[]> GetAllPhotosAsync()
    {
        return base.Channel.GetAllPhotosAsync();
    }
    
    public MyPhotos.Proxy.Person[] GetAllPersons()
    {
        return base.Channel.GetAllPersons();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Person[]> GetAllPersonsAsync()
    {
        return base.Channel.GetAllPersonsAsync();
    }
    
    public MyPhotos.Proxy.Event[] GetAllEvents()
    {
        return base.Channel.GetAllEvents();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Event[]> GetAllEventsAsync()
    {
        return base.Channel.GetAllEventsAsync();
    }
    
    public MyPhotos.Proxy.Landscape[] GetAllLandscapes()
    {
        return base.Channel.GetAllLandscapes();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Landscape[]> GetAllLandscapesAsync()
    {
        return base.Channel.GetAllLandscapesAsync();
    }
    
    public MyPhotos.Proxy.Place[] GetAllPlaces()
    {
        return base.Channel.GetAllPlaces();
    }
    
    public System.Threading.Tasks.Task<MyPhotos.Proxy.Place[]> GetAllPlacesAsync()
    {
        return base.Channel.GetAllPlacesAsync();
    }
}
