//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPhotosEntities : DbContext
    {
        public MyPhotosEntities()
            : base("name=MyPhotosEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Landscape> Landscapes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
    }
}
